### PR TITLE
Create test-modification-01.txt

### PR DESCRIPTION
**Pull request by vverecke**
Test merge into protected target branch with required status checks (enforced in github + bulldozer.yml)
This will be triggered using a label

### CODE REVIEW

**Review by 1inh — APPROVED** [review]

**Comment by vverecke** [comment]
Sent a "failure" moch check to prevent the initial auto-merge, and enable myself to add said check (context : Mock check) as a required one under branch protection settings for develop.
image

**Comment by vverecke** [comment]
Bulldozer update please!

**Comment by vverecke** [comment]
Bulldozer update please!

**Comment by vverecke** [comment]
Test is a success, trimmed logs from the bulldozer app: 

```
"message":"Attempting to merge pull request with method squash"}
"message":"github_request"}
"message":"Successfully merged pull request as SHA 19794fe6f33e2383cfb0c55c0342cfb54f113a6c"}
"message":"github_request"}
"message":"Attempting to delete ref refs/heads/test-merge-into-protected-with-checks-gh-and-bulldozer"}
"message":"Received webhook event"}
"message":"http_request"}
"message":"Doing nothing since pull request is closed"}
```

**Comment by vverecke** [comment]
image
 **Test merge into protected target branch with required status checks** (enforced in github + bulldozer.yml) ✔️
 **Test merge into protected target branch with required status checks** (enforced only in github) ✔️
Status check with context `Mock Check`  is set in GH/Branch protection
 **Test merge into protected target branch with required status checks** (enforced only in bulldozer.yml) ✔️ 
Status check with context `auto-merge-extra-status` is set as an additional requirement in bulldozer.yml

**Pull request merged**
